name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build --file ./Dockerfile ./ --tag ecs-image-processor:$(date +%s)
    - name: Install AWS CLI v2
      run:  |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o /tmp/awscliv2.zip
          unzip -q /tmp/awscliv2.zip -d /tmp
          rm /tmp/awscliv2.zip
          sudo /tmp/aws/install --update
          rm -rf /tmp/aws/
    - name: Obtain ECS Credential
      run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 578400831858.dkr.ecr.us-east-1.amazonaws.com
      
